### PR TITLE
fix seo crap

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Oxygemo <alej0hio2007@gmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
image

**Review by akisblack — CHANGES_REQUESTED** [review]
send a ss without using vivaldi

**Comment by ghost** [comment]
oh thats gonna be hard

**Comment by ghost** [comment]
image
ok this time i took it in ungoogled chromium

**Review by akisblack — APPROVED** [review]

**Pull request merged**
